### ISSUE TITLE
understand the data and check the results

### ISSUE THREAD

**Issue by kristina-monsch** [kristina-monsch/ammonia_project#22]
- [x] look at the spectrum in the data cube itself and compare this to the masked cube; how does the continuum behave?
- [x] what is the proper value for sigma? in which way should the Orion BN/KL region be "filtered" out from the analysis (generously cut it out or just exclude certain pixels?) do we want to lose the pixels that are cut out this way?
- [x] adjust the limits in the moment maps and check them

**Comment by kristina-monsch** [comment]
Some things have been done in commit #23

**Comment by jpinedaf** [comment]
Indeed, looking forward for your answers ;)

**Comment by kristina-monsch** [comment]
**result:**
a value of the continuum snr between 3 and 5 should be the best choice, because then most parts of the filament are preserved, while the dense core in the south is mostly filtered out. 
if cont_snr < 3: too much of the filament is cut out
if cont_snr > 5: too much of the dence core is left
for 3 < cont_snr < 5: the shape of the filament does not really change much, only the denser parts in the middle and the core in the south

**now:**

- [ ] check whether the fits are reasonable and decrease the peak snr to have a broader overview of the data cube
- [ ] let the code run again with very low peak snr (i.e. 0.1 or so) so that as many pixels as possible are fitted. The only restriction now will be our planemask with cont_snr = 3.0, all of the other masking can happen after the fit has been run

**Comment by kristina-monsch** [comment]
see #24

**Comment by kristina-monsch** [comment]
Hi Jaime,

I let the code run again (without using the remove_small_objects before the fit), could you please check the fitted data cube? --> https://github.com/kristina-monsch/ammonia_project/blob/update_moment0_map/parameter_maps/VLA_GBT/OrionA_parameter_maps_peaksnr1_contsnr3.fits

**Comment by kristina-monsch** [comment]
Hi Jaime, I have rerun the code, but I'm still not sure about the results...
The fit does look better in general (f.ex. the linewidth map) but especially the temperature maps still look much like Swiss cheese. I changed the range for the fitting parameters to 2.8 K - 300 K which seemed very generous of me but there are still a lot of pixels that reach these high temperatures. Also it looks like there are some kind of "hot regions", does this make sense?
First I attach some screenshots of these hot regions:
![hot_regions_1](https://cloud.githubusercontent.com/assets/18168392/23344452/07d96188-fc7d-11e6-9a28-1b499a7d2a00.png)
![hot_regions_2](https://cloud.githubusercontent.com/assets/18168392/23344454/07db205e-fc7d-11e6-8335-7528b48bfc22.png)
![tkin_wholemap](https://cloud.githubusercontent.com/assets/18168392/23344453/07da6010-fc7d-11e6-8b34-ccd999cbfce6.png)
 
I also checked the spectra of some pixels (especially those with high temperatures to understand what's going on) and the fits mostly look horrible. Could it be, that the slab I've used is too broad? The code is still trying to fit the second satellite component, could this be the cause?

[272_584.pdf](https://github.com/kristina-monsch/ammonia_project/files/802352/272_584.pdf)
[274_584.pdf](https://github.com/kristina-monsch/ammonia_project/files/802357/274_584.pdf)
[276_584.pdf](https://github.com/kristina-monsch/ammonia_project/files/802354/276_584.pdf)
[278_591.pdf](https://github.com/kristina-monsch/ammonia_project/files/802355/278_591.pdf)
[322_321.pdf](https://github.com/kristina-monsch/ammonia_project/files/802356/322_321.pdf)
[328_316.pdf](https://github.com/kristina-monsch/ammonia_project/files/802353/328_316.pdf)
[409_170.pdf](https://github.com/kristina-monsch/ammonia_project/files/802358/409_170.pdf)


I also can't really find a connection between horrible temperature fits and other fitting parameters, such as sigma. I'm attaching a screenshot for first view, it looks really complete to me and not so bad actually. But please bear with me, that I've still not applied the remove_small_objects function, I still haven't figured out how exactly to apply it onto the fitted parameters...
![sigma](https://cloud.githubusercontent.com/assets/18168392/23344490/b718dcbe-fc7d-11e6-86e5-d625de229c03.png)

Thank you really much for your help!

**Comment by jpinedaf** [comment]
The temperatures are usually hard to get if there is not enough signal. In this case, many points have issues with the Tex, which is related to the shape of the NH3(1,1) line, while when the problem is with the Tkin then the problem could lie with some of the poor detections of NH3(2,2).

Also, remember that the Tkin is the gas temperature, and that Tex is lower than Tkin

In any case, looking at some of your examples:
272_584.pdf, 274_584.pdf and 276_584.pdf   are probably affected by two components along the line of sight, and a really bad satellite (at velocities lower than -5 km/s). 
278_591.pdf   has a line that is in a velocity range beyond your window (I think)
322_321.pdf, I'm not sure, but it could be related to the satellite at low velocities. It could also depend on the NH3(2,2)
328_316.pdf, there is something strange about this spectrum: the second component seen in the first pair of satellites should also be seen on the main blend... which is not present. What does the NH3(2,2) looks like?
409_170.pdf: 2 components! this is a messy spectrum, no fit will work here ;-)

**Comment by kristina-monsch** [comment]
Thanks for your feedback! I saved the parameter maps in the master branch now and rerun the fit with changed slab in another branch again, just to see whether this improves the results..The fit should be done tomorrow :) 
But this also means that I can't change that much about the temperatures and should just flag them properly for the analysis, right?

**Comment by kristina-monsch** [comment]
Here are the histograms of the fitted parameters, they all look reasonable to me: 
![fitted_parameters_hist_vc](https://cloud.githubusercontent.com/assets/18168392/23859519/22390aa0-0804-11e7-9245-457b412b9a40.png)
![hist_dv](https://cloud.githubusercontent.com/assets/18168392/23859523/2242a7c2-0804-11e7-8e7a-0343ced4f002.png)
![hist_nnh3_flag](https://cloud.githubusercontent.com/assets/18168392/23859521/223bcef2-0804-11e7-9c2d-f091a5590d8d.png)
![hist_tex_flag](https://cloud.githubusercontent.com/assets/18168392/23859524/2253ff90-0804-11e7-9450-13647f74a428.png)
![hist_tk_flag](https://cloud.githubusercontent.com/assets/18168392/23859520/223ae42e-0804-11e7-94d4-0b6f3594bea6.png)

**Comment by kristina-monsch** [comment]
Here the spectra of some regions, where I wanted to check the behavior of the fits...I chose especially those regions where the hot pixels pile up. What I have noticed is, that there still are these thread-like structures, were the fit is completely off. I don't know what to do about them, is there anything?

![313_508_full](https://cloud.githubusercontent.com/assets/18168392/23860646/d9ab6d74-0807-11e7-98ea-3e2177f5dc7a.png)
![314_507_full](https://cloud.githubusercontent.com/assets/18168392/23860647/d9abd3e0-0807-11e7-8b10-08b5671a20c5.png)
![315_508_full](https://cloud.githubusercontent.com/assets/18168392/23860648/d9ac3b3c-0807-11e7-9164-a6bb36540f70.png)
![316_508](https://cloud.githubusercontent.com/assets/18168392/23860649/d9ac5130-0807-11e7-8e4f-798ab5c9c161.png)
![317_508](https://cloud.githubusercontent.com/assets/18168392/23860651/d9afe750-0807-11e7-9f65-ef09be114df8.png)
![318_508](https://cloud.githubusercontent.com/assets/18168392/23860650/d9adb2fa-0807-11e7-88c2-54a854066d80.png)
![346_208](https://cloud.githubusercontent.com/assets/18168392/23860652/d9c00266-0807-11e7-965f-e8395a408c8a.png)
![367_608](https://cloud.githubusercontent.com/assets/18168392/23860654/d9c22280-0807-11e7-8eea-973699981445.png)
![371_591](https://cloud.githubusercontent.com/assets/18168392/23860653/d9c0f39c-0807-11e7-8a93-27d786d336ca.png)
![372_590](https://cloud.githubusercontent.com/assets/18168392/23860655/d9c4350c-0807-11e7-88ee-f4055937db42.png)
![379_610](https://cloud.githubusercontent.com/assets/18168392/23860657/d9c6d262-0807-11e7-9ae8-4bf5964108c6.png)
![386_582](https://cloud.githubusercontent.com/assets/18168392/23860656/d9c4e7fe-0807-11e7-9202-eec08a7a9d66.png)
![387_582](https://cloud.githubusercontent.com/assets/18168392/23860658/d9d3c7f6-0807-11e7-957d-e11782b9959f.png)
![388_582](https://cloud.githubusercontent.com/assets/18168392/23860659/d9d7e3e0-0807-11e7-8b3e-a310e4aac1d5.png)
![389_582](https://cloud.githubusercontent.com/assets/18168392/23860660/d9db9076-0807-11e7-8383-102077d9b622.png)

**Comment by kristina-monsch** [comment]
this issue was addressed in the pyspeckit issue #220 and will be further discussed in issue #39
