### ISSUE TITLE
improve/update integrated intensity maps

### ISSUE THREAD

**Issue by kristina-monsch** [kristina-monsch/ammonia_project#33]
try to improve the moment0 map by using http://gas.readthedocs.io/en/latest/Update_NH3_mom0.html for our data...

situation: moment0 map only includes the emission from the main component of the ammonia line 
--> this function uses the results from the previous line fitting to determine the channel range with signal for the integrated intensity calculation

```python import GAS
import GAS.PropertyMaps
GAS.PropertyMaps.update_NH3_moment0(region_name='OrionA', file_extension='_DR1', threshold=0.0125, save_masked=True)`

**Comment by kristina-monsch** [comment]
I was able to implement the function (but it was not that easy due to our different naming schemes ;)
Anyway, I managed to let the function run on my data. The "improved" moment0 looks strange, like there are many pixels missing. But in general I can definitely see an improvement, it looks "sharper" and not so blurred anymore, I guess.
I only included the (1,1) line for this routine, I think I should also use the (2,2) line, which might improve the moment0 map. I will keep you updated!

left: improved/updated moment0 map
right: original data

![comparison_moment0_maps](https://cloud.githubusercontent.com/assets/18168392/22044172/8894d534-dd13-11e6-94a1-56538ffa5c9c.png)
![comparison_moment0_maps_1](https://cloud.githubusercontent.com/assets/18168392/22044173/8895672e-dd13-11e6-89c8-bcb0a15f6e0a.png)
![comparison_moment0_maps_2](https://cloud.githubusercontent.com/assets/18168392/22044174/8895d59c-dd13-11e6-9e74-994ab0deb155.png)

See pull request #34

**Comment by jpinedaf** [comment]
when we meet, could you please bring the data cubes and the masked datacube that can be created by the improved integrated intensity function?

**Comment by kristina-monsch** [comment]
They are on Github now: https://github.com/kristina-monsch/ammonia_project/tree/update_moment0_map/data/VLA_GBT

I have also run the function with the (2,2) line, but they improved moment map still looks the same...(of course, because why would it? I did not really think about this yesterday..)
Anyway, I've used it this way: https://github.com/kristina-monsch/ammonia_project/blob/update_moment0_map/update_moment0.py Please ignore the horrible coding style, I did not want to change the names of all of my data........-.-

**Comment by kristina-monsch** [comment]
Here are the screenshots for peak_snr=20 as comparison:
![comparison_moment0_snr20_1](https://cloud.githubusercontent.com/assets/18168392/22085276/a1b2fe54-ddd3-11e6-9fa3-70a5a0f3ea75.png)
![comparison_moment0_snr20_2](https://cloud.githubusercontent.com/assets/18168392/22085277/a1b314d4-ddd3-11e6-9a25-e3f1e487bd26.png)
![comparison_moment0_snr20_3](https://cloud.githubusercontent.com/assets/18168392/22085278/a1b65a68-ddd3-11e6-9ce3-52d0116e319c.png)
![comparison_moment0_snr20_4](https://cloud.githubusercontent.com/assets/18168392/22085279/a1b8e008-ddd3-11e6-8682-5ef93626e93b.png)
![comparison_moment0_snr20_5](https://cloud.githubusercontent.com/assets/18168392/22085280/a1ba592e-ddd3-11e6-9738-63776f2de319.png)

I don't know if this is worth the effort..? Or did I miss something in my code?

**Comment by jpinedaf** [comment]
also update this https://github.com/kristina-monsch/ammonia_project/blob/922852a38d1f4605c94b41154d3f7d4b66040dec/linefit_plotting.py#L142
to use proper contour levels, as in casaviewer

**Comment by jpinedaf** [comment]
check that original moment-0 map does not include masked pixels (black pixels)

**Comment by kristina-monsch** [comment]
This method relies on the fitted parameters and can only be used if there are good fits available. Since there are many pixels in the old fit, this does not work for the unsmoothed cube. I'm currently checking the smoothed cube to see whether here the results might improve. The screenshots will follow tomorrow!
