### ISSUE TITLE
make plots of fitted parameters

### ISSUE THREAD

**Issue by jpinedaf** [kristina-monsch/ammonia_project#5]
Here is an example of how to plot them
https://github.com/GBTAmmoniaSurvey/GAS/blob/master/GAS/PropertyMaps.py#L278

**Comment by kristina-monsch** [comment]
#4

**Comment by jpinedaf** [comment]
- [ ] map of integrated intensity for NH3 (1,1) and (2,2)
- [ ] Vlsr map
- [ ] sigma_v map
- [ ] Tex map
- [ ] Tkin map
- [ ] Column density map

**Comment by kristina-monsch** [comment]
**#10: added plotting routines**

I've added the basic plotting routines and at least it's plotting, but I still have to check whether it's plotting the right thing.

**Comment by kristina-monsch** [comment]
#12: plotting the fitted parameter is working now

**Comment by kristina-monsch** [comment]
#13 now everything is up-to-date, see the pull request :)
