### ISSUE TITLE
update code to use new cold NH3 model

### ISSUE THREAD

**Issue by jpinedaf** [kristina-monsch/ammonia_project#6]
There is an updated version of the NH3 modelling:

https://github.com/pyspeckit/pyspeckit/pull/170

**Comment by jpinedaf** [comment]
in particular look at this notebook: https://github.com/keflavich/pyspeckit/blob/90ff0f6bb9a12762fee80d65f99da9621a485489/examples/AmmoniaLevelPopulation.ipynb

**Comment by jpinedaf** [comment]
@kristina-monsch notice that there is a new release of pyspeckit... v0.1.19, which now includes a `cold_ammonia` model to do this.

**Comment by jpinedaf** [comment]
check the function in the GAS pipeline: https://github.com/GBTAmmoniaSurvey/GAS/blob/master/GAS/PropertyMaps.py#L790
which includes the limits to the parameters that we discussed, including column density and then update 
https://github.com/kristina-monsch/ammonia_project/blob/improved_plot/coldammonia_fit.py#L118

**Comment by kristina-monsch** [comment]
The cold_ammonia fit runs properly but `pcube.plot_spectrum()` is now causing problems:

> ---------------------------------------------------------------------------
> 
> ValueError                                Traceback (most recent call last)
> <ipython-input-11-b1d14111cada> in <module>()
> ----> 1 pcube.plot_spectrum(xmax, ymax, plot_fit=True)
> 
> /home/monsch/Desktop/NH3/pyspeckit/pyspeckit/cubes/SpectralCube.pyc in plot_spectrum(self, x, y, plot_fit, **kwargs)
>     341             self.plotter(**kwargs)
>     342             if plot_fit:
> --> 343                 self.plot_fit(x,y)
>     344             self.plotted_spectrum = self
>     345         else:
> 
> /home/monsch/Desktop/NH3/pyspeckit/pyspeckit/cubes/SpectralCube.pyc in plot_fit(self, x, y, silent, **kwargs)
>     385         self.specfit.npeaks = self.specfit.fitter.npeaks
>     386         self.specfit.model = self.specfit.fitter.n_modelfunc(self.specfit.modelpars,
> --> 387                                                              **self.specfit.fitter.modelfunc_kwargs)(self.xarr)
>     388 
>     389         # set the parinfo values correctly for annotations
> 
> /home/monsch/Desktop/NH3/pyspeckit/pyspeckit/spectrum/models/ammonia.py in L(x)
>     444                     name = parnames[ii+jj*int(npars)].strip('0123456789').lower()
>     445                     modelkwargs.update({name:parvals[ii+jj*int(npars)]})
> --> 446                 v += self.modelfunc(x,**modelkwargs)
>     447             return v
>     448         return L
> 
> /home/monsch/Desktop/NH3/pyspeckit/pyspeckit/spectrum/models/ammonia.py in cold_ammonia(xarr, tkin, **kwargs)
>     248     log.debug("Cold ammonia turned T_K = {0} into T_rot = {1}".format(tkin,trot))
>     249 
> --> 250     return ammonia(xarr, trot=trot, **kwargs)
>     251 
>     252 def ammonia_thin(xarr, tkin=20, tex=None, ntot=14, width=1, xoff_v=0.0,
> 
> /home/monsch/Desktop/NH3/pyspeckit/pyspeckit/spectrum/models/ammonia.py in ammonia(xarr, trot, tex, ntot, width, xoff_v, fortho, tau, fillingfraction, return_tau, background_tb, verbose, return_components, debug, line_names)
>     122         lin_ntot = 10**ntot
>     123     else:
> --> 124         raise ValueError("ntot, the logarithmic total column density,"
>     125                          " must be in the range 5 - 25")
>     126 
> 
> ValueError: ntot, the logarithmic total column density, must be in the range 5 - 25

 I don't know where this comes from, because `ntot` is defined in the ammonia function as well as in our guesses! I tried to define `ntot` globally but this doesn't change anything. I also noticed that in the `cold_ammonia` function we return ammonia:

```python
   def cold_ammonia(xarr, tkin, **kwargs):
    """
    Generate a model Ammonia spectrum based on input temperatures, column, and
    gaussian parameters

    Parameters
    ----------
    xarr: `pyspeckit.spectrum.units.SpectroscopicAxis`
        Array of wavelength/frequency values
    tkin: float
        The kinetic temperature of the lines in K.  Will be converted to
        rotational temperature following the scheme of Swift et al 2005
        (http://esoads.eso.org/abs/2005ApJ...620..823S, eqn A6) and further
        discussed in Equation 7 of Rosolowsky et al 2008
        (http://adsabs.harvard.edu/abs/2008ApJS..175..509R)
    """
    
    dT0 = 41.18 # Energy difference between (2,2) and (1,1) in K
    trot = tkin * (1 + (tkin/dT0)*np.log(1 + 0.6*np.exp(-15.7/tkin)))**-1
    log.debug("Cold ammonia turned T_K = {0} into T_rot = {1}".format(tkin,trot))

    return ammonia(xarr, trot=trot, **kwargs)
```

Is this correct or should we return the `cold_ammonia` class here? I'm wondering because the whole code ran properly when I used the ammonia fittype and the problem with the `.run_spectrum()` has not occured until I changed the fittype to cold_ammonia.

Note: I've created a jupyter notebook to test parts of the code seperately, it's called:  coldammonia_fit.ipynb . But it does not include the plots etc. yet !

**Comment by jpinedaf** [comment]
notice that to include the plots in the ipython notebook you should use ``` %matplotlib inline``` in the first line, see [link](http://stackoverflow.com/questions/19410042/how-to-make-ipython-notebook-matplotlib-plot-inline)

**Comment by kristina-monsch** [comment]
**Update**

I made the whole code from scratch again because I wasn't able to get rid of the error message, no matter what I did. The `ntot` error is now gone, but now it gives me the following error message:

> INFO: Fitting  207, 184 (s/n=42) [pyspeckit.cubes.SpectralCube]
> INFO: Using input guess cube [pyspeckit.cubes.SpectralCube]
> INFO: Finished fit      1 of     18 at ( 207, 184) s/n= 42.1. Elapsed time is 0.3 seconds.  %6 [pyspeckit.cubes.SpectralCube]
> 
> ERROR: Fit number 0 at 207,184 failed on error 12.0 is greater than the upper limit 0 [pyspeckit.cubes.SpectralCube]
> ERROR: Failure was in file /home/monsch/Desktop/NH3/pyspeckit/pyspeckit/cubes/SpectralCube.py at line 854 [pyspeckit.cubes.SpectralCube]
>   File "/home/monsch/Desktop/NH3/pyspeckit/pyspeckit/cubes/SpectralCube.py", line 854, in fit_a_pixel
>     verbose=verbose_level>3, **fitkwargs)
>   File "/home/monsch/Desktop/NH3/pyspeckit/pyspeckit/config.py", line 145, in decorator
>     f(self, *args, **new_kwargs)
>   File "/home/monsch/Desktop/NH3/pyspeckit/pyspeckit/spectrum/fitters.py", line 312, in __call__
>     guesses=guesses, annotate=annotate, **kwargs)
>   File "/home/monsch/Desktop/NH3/pyspeckit/pyspeckit/spectrum/fitters.py", line 661, in multifit
>     new_guesses = self._validate_parinfo(pinf, 'guesses')
>   File "/home/monsch/Desktop/NH3/pyspeckit/pyspeckit/spectrum/fitters.py", line 2004, in _validate_parinfo
>     .format(param.value, param.limits[1]))
> ERROR: Guesses were: [ 12.           3.          14.5          2.768874    35.34738718   0.        ] [pyspeckit.cubes.SpectralCube]
> ERROR: Fitkwargs were: {'limitedmin': [True, True, True, True, True, True], 'fittype': 'cold_ammonia', 'fixed': [True, False, False, False, False, True], 'limitedmax': [True, False, True, False, False, True]} [pyspeckit.cubes.SpectralCube]
> 
> ---------------------------------------------------------------------
> AssertionError                      Traceback (most recent call last)
> <ipython-input-6-f7c1117a6756> in <module>()
>      15                   limitedmin=[T,T,T,T,T,T],
>      16                   position_order = 1/peaksnr, maskmap=planemask,
> ---> 17                   multicore=2)
>      18 
>      19     #save the fit parameters in a FITS-file otherwise the fit would be lost!!!
> 
> /home/monsch/Desktop/NH3/pyspeckit/pyspeckit/cubes/SpectralCube.pyc in fiteach(self, errspec, errmap, guesses, verbose, verbose_level, quiet, signal_cut, usemomentcube, blank_value, integral, direct, absorption, use_nearest_as_guess, use_neighbor_as_guess, start_from_point, multicore, position_order, continuum_map, prevalidate_guesses, maskmap, **fitkwargs)
>     924                 raise ex
>     925         except AssertionError:
> --> 926             raise AssertionError("The first pixel had the wrong fit "
>     927                                  "parameter shape.  This is probably "
>     928                                  "a bug; please report it.")
> 
> AssertionError: The first pixel had the wrong fit parameter shape.  This is probably a bug; please report it.

I fixed Tkin but can it be that my limits are wrong? I set that limitedmax and limitedmin are both True for Tkin and ntot. Is this right?

Please have a look at the "new_linefit" notebook: [https://github.com/kristina-monsch/ammonia_project/blob/improved_plot/new_linefit.ipynb ](url)

#10

**Comment by kristina-monsch** [comment]
#13 the cold_ammonia fitting routine is now included, see the linefit_160821.py file
